### ISSUE TITLE
repr(C) "equivalent to repr(u32) for enums"

### ISSUE THREAD

**Issue by sp3d** [Gankro/turpl#12]
It's common, but definitely not universal (see -fshort-enums) for C compilers to represent enums with 32 bits. Could TURPL mention this subtlety and clarify the justification for Rust simply assuming C to use 32-bit enum representation (if that's indeed what rustc does)?

This thread seems relevant: http://gcc.gnu.org/ml/gcc/2005-09/msg00728.html

**Comment by Gankro** [comment]
CC @bluss

**Comment by Gankro** [comment]
Ah actually the reference actually specifies exactly what you're saying! Will fix.

**Comment by Gankro** [comment]
Fixed:

* This is equivalent to one of `repr(u*)` (see the next section) for enums. The
  chosen size is the default enum size for the target platform's C ABI. Note that
  enum representation in C is undefined, and this may be incorrect when the C
  code is compiled with certain flags.

**Comment by bluss** [comment]
I like saying implementation defined instead.

C libs usually avoid having enums in their API because different compilers can compile them differently.
