### ISSUE TITLE
repr(packed) section could be more careful talking about architectures' alignment requirements

### ISSUE THREAD

**Issue by sp3d** [Gankro/turpl#13]
Generally the section is very good and I agree with the sentiment expressed in the following paragraph:

```In particular, most architectures strongly prefer values to be aligned. This may mean the unaligned loads are penalized (x86), or even fault (ARM). In particular, the compiler may have trouble with references to unaligned fields.```

But it isn't true that ARM always faults on unaligned loads, and ARMv7 and up do not fault because of unaligned accesses to half or full words.

For gory details, see:
http://www.heyrick.co.uk/armwiki/Unaligned_data_access
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka15414.html
but I would think it might be better just to say "some ARM chips" in the parenthetical, since explaining any of this in much detail would be a digression from the Rust attrs being discussed.

Also, I'm not sure what "compiler may have trouble" implies; that sentence is more confusing than informative.

**Comment by Gankro** [comment]
Changed it to:

In particular, most architectures *strongly* prefer values to be aligned. This
may mean the unaligned loads are penalized (x86), or even fault (some ARM chips).
For simple cases like directly loading or storing a packed field, the compiler
might be able to paper over alignment issues with shifts and masks. However if
you take a reference to a packed field, it's unlikely that the compiler will be
able to emit code to avoid an unaligned load.
