### ISSUE TITLE
explain what ghc is

### ISSUE THREAD

**Issue by vks** [Gankro/turpl#7]
In the chapter about tagged unions:

```
This means that they can in principle keep their data inline (ghc has a pragma for this).
```

I think some readers might be confused here not knowing what ghc is.

**Comment by Gankro** [comment]
On the advisement of several people, I'll probably be rewriting this section to just use Box instead, which should be simpler and remove this reference altogether.

(I still think the tagged union thing is really cool, but oh well...)

**Comment by Gankro** [comment]
This reference has been removed entirely.
